# Generated by Django 6.0.1 on 2026-01-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tuổi'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='current_weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Cân nặng hiện tại (kg)'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='goal',
            field=models.CharField(choices=[('GAIN', 'Tăng cơ / Tăng cân'), ('LOSE', 'Giảm cân'), ('MAINTAIN', 'Duy trì')], default='MAINTAIN', max_length=10, verbose_name='Mục tiêu'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Người dùng'), ('COACH', 'Huấn luyện viên / Chuyên gia')], default='USER', max_length=10, verbose_name='Vai trò'),
        ),
    ]
