# Generated by Django 6.0.1 on 2026-01-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_healthprofile_bmi_alter_healthprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
