# Generated by Django 6.0.1 on 2026-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailymetric_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymetric',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nhịp tim (bpm)'),
        ),
    ]
