# Generated by Django 6.0.1 on 2026-01-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='daily_calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lượng calo hàng ngày'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='daily_carbs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lượng carb hàng ngày'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='daily_fats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lượng chất béo hàng ngày'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='daily_protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lượng protein hàng ngày'),
        ),
    ]
